import { auth, db, adminEmail } from './firebase-config.js';
import { onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { collection, doc, writeBatch, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const people=['AMADEU','BAIXINHO','BRENKE','CAUE RENAN','DIEGO','COVELLI','JOTA','KAUAN','NEIVA','LARISSA','LÉO AVILA','LÉO MEIRA','LUIZ','MENDES','MILTON','PEDRINHO','TECO'];
const r19=[['Fluminense','Bragantino'],['Botafogo','Santos'],['São Paulo','Athletico'],['Corinthians','Remo'],['Mirassol','Grêmio'],['Atlético-MG','Bahia'],['Internacional','Cruzeiro'],['Coritiba','Palmeiras'],['Vitória','Vasco'],['Chapecoense','Flamengo']];
const log=t=>document.querySelector('#log').textContent=t;
let allowed=false;onAuthStateChanged(auth,u=>{allowed=!!u&&u.email===adminEmail;log(allowed?'Admin autenticado. Selecione o TXT e importe.':'Entre como Admin antes de abrir esta página.');});
function fixtures(text){const rs=[...text.matchAll(/RODADA (\d{2})\n\nJOGOS:\n([\s\S]*?)\n\nPALPITES:/g)].map((m)=>({number:+m[1],games:[...m[2].matchAll(/^\d+\.\s+(.+?)\s+x\s+(.+)$/gm)].map((g,i)=>({home:g[1],away:g[2],order:i+1,status:+m[1]===4&&i>=7?'postponed':'scheduled'}))}));rs.push({number:19,games:r19.map(([home,away],i)=>({home,away,order:i+1,status:'scheduled'}))});return [...rs,...rs.map(r=>({number:r.number+19,returnOf:r.number,games:r.games.map(g=>({home:g.away,away:g.home,order:g.order,status:'scheduled'}))}))];}
async function commit(docs){for(let i=0;i<docs.length;i+=400){const b=writeBatch(db);docs.slice(i,i+400).forEach(x=>b.set(x.ref,x.data,{merge:true}));await b.commit();log(`Importando… ${Math.min(i+400,docs.length)}/${docs.length}`);}}
document.querySelector('#import').onclick=async()=>{if(!allowed)return log('Acesso administrativo necessário.');const f=document.querySelector('#file').files[0];if(!f)return log('Escolha o TXT histórico.');try{const text=await f.text();const rs=fixtures(text);const docs=[];people.forEach((name,i)=>docs.push({ref:doc(db,'participants',`p${i+1}`),data:{name,order:i+1,active:true,createdAt:serverTimestamp()}}));rs.forEach(r=>{docs.push({ref:doc(db,'rounds',`r${r.number}`),data:{number:r.number,returnOf:r.returnOf||null}});r.games.forEach(g=>docs.push({ref:doc(db,'games',`r${r.number}-g${g.order}`),data:{round:r.number,order:g.order,home:g.home,away:g.away,status:g.status,originalRound:r.number}}));});for(const block of text.matchAll(/RODADA (\d{2})[\s\S]*?PALPITES:\n([\s\S]*?)(?=\n={6,}|$)/g)){const round=+block[1],body=block[2];people.forEach((name,p)=>{const part=body.split(`\n${name}\n`)[1]?.split(/\n[A-ZÁÉÍÓÚÂÊÔÃÇ ]+\n/)[0]||'';for(const m of part.matchAll(/^(\d+)\.\s+(.+)$/gm)){const raw=m[2].trim();if(raw==='-')continue;const hit=raw.match(/(\d+)x(\d+)(?:\s+(.+))?/);if(hit)docs.push({ref:doc(db,'predictions',`r${round}-p${p+1}-g${m[1]}`),data:{round,participant:`p${p+1}`,game:`r${round}-g${m[1]}`,homeGoals:+hit[1],awayGoals:+hit[2],firstGoal:hit[3]||null,imported:true}});}});}await commit(docs);log(`Concluído: ${docs.length} registros importados.`);}catch(e){console.error(e);log(`Erro: ${e.message}`);}};
