export const PARTICIPANTS = [
  { id: 'p1', name: 'AMADEU' },
  { id: 'p2', name: 'BAIXINHO' },
  { id: 'p3', name: 'BRENKE' },
  { id: 'p4', name: 'CAUE RENAN' },
  { id: 'p5', name: 'DIEGO' },
  { id: 'p6', name: 'COVELLI' },
  { id: 'p7', name: 'JOTA' },
  { id: 'p8', name: 'KAUAN' },
  { id: 'p9', name: 'NEIVA' },
  { id: 'p10', name: 'LARISSA' },
  { id: 'p11', name: 'LÉO AVILA' },
  { id: 'p12', name: 'LÉO MEIRA' },
  { id: 'p13', name: 'LUIZ' },
  { id: 'p14', name: 'MENDES' },
  { id: 'p15', name: 'MILTON' },
  { id: 'p16', name: 'PEDRINHO' },
  { id: 'p17', name: 'TECO' },
];
