export const SQUADS = {
  Palmeiras: [
    'ZAG • Murilo', 'ZAG • Bruno Fuchs', 'ZAG • Luis Benedetti', 'ZAG • Gustavo Gómez',
    'LE • Joaquín Piquerez', 'LE • Jefté', 'LE • Arthur Gabriel', 'LD • Agustín Giay',
    'LD • Khellven', 'VOL • Emiliano Martínez', 'VOL • Marlon Freitas', 'VOL • Luis Pacheco',
    'MC • Andreas Pereira', 'MC • Lucas Evangelista', 'MC • Larson', 'MEI • Maurício',
    'MEI • Erick Belé', 'PE • Felipe Anderson', 'PE • Riquelme Filippi', 'PD • Allan',
    'PD • Jhon Arias', 'SA • Ramón Sosa', 'SA • Paulinho', 'ATA • Vitor Roque',
    'ATA • Flaco López', 'ATA • Luighi',
  ],
  Flamengo: [
    'ZAG • Léo Ortiz', 'ZAG • Léo Pereira', 'ZAG • Vitão', 'ZAG • Danilo', 'ZAG • João Souza',
    'LE • Ayrton Lucas', 'LE • Alex Sandro', 'LD • Emerson Royal', 'LD • Guillermo Varela',
    'VOL • Everton Araújo', 'VOL • Erick Pulgar', 'VOL • Jorginho', 'MC • Nicolás de la Cruz',
    'MC • Saúl Ñíguez', 'MC • Lucas Paquetá', 'MEI • Giorgian De Arrascaeta',
    'MEI • Jorge Carrascal', 'PE • Samuel Lino', 'PE • Everton', 'PD • Gonzalo Plata',
    'PD • Luiz Araújo', 'ATA • Pedro', 'ATA • Wallace Yan', 'ATA • Bruno Henrique',
  ],
  Cruzeiro: [
    'ZAG • Jonathan Jesus', 'ZAG • João Marcelo', 'ZAG • Lucas Villalba', 'ZAG • Bruno Alves',
    'ZAG • Janderson', 'LE • Kaiki', 'LD • Kauã Prates', 'LD • William', 'LD • Kauã Moraes',
    'LD • Fagner', 'VOL • Wallace', 'VOL • Lucas Romero', 'VOL • Murilo Rhikman',
    'VOL • Lucas Silva', 'MC • Gerson', 'MC • Christian', 'MC • Matheus Henrique', 'MC • Japa',
    'MEI • Matheus Pereira', 'PE • Luis Sinisterra', 'PE • Kaique Kenji', 'PE • Wanderson',
    'PE • Bruno Rodrigues', 'PD • Keny Arroyo', 'PD • Marquinhos', 'ATA • Kaio Jorge',
    'ATA • Néiser Villarreal', 'ATA • Chico da Costa',
  ],
  Corinthians: [
    'ZAG • Tchoca', 'ZAG • André Ramalho', 'ZAG • Gustavo Henrique', 'ZAG • Gabriel Paulista',
    'ZAG • Renato Santos', 'LE • Matheus Bidu', 'LE • Hugo', 'LE • Fabrizio Angileri',
    'LD • Matheuzinho', 'LD • Pedro Milans', 'VOL • Raniele', 'VOL • Allan', 'VOL • Charles',
    'MC • Breno Bidon', 'MC • André', 'MC • Matheus Pereira', 'MC • Alex Santana',
    'MC • André Carrillo', 'MC • Bahia', 'MEI • Rodrigo Garro', 'MEI • Jesse Lingard',
    'MEI • Zakarai Labeyad', 'PE • Kayke', 'PE • Vitinho', 'PD • Kaio César',
    'PD • Dieguinho', 'ATA • Yuri Alberto', 'ATA • Memphis Depay', 'ATA • Gui Negão',
    'ATA • Pedro Raul',
  ],
  Botafogo: [
    'ZAG • Alexander Barboza', 'ZAG • Nahuel Ferraresi', 'ZAG • Kaio', 'ZAG • Bastos',
    'ZAG • Ythallo', 'ZAG • Anthony', 'LE • Alex Telles', 'LE • Marçal',
    'LE • Jhohan Hernández', 'LE • Caio Roque', 'LD • Vitinho', 'LD • Mateo Ponte',
    'VOL • Newton', 'VOL • Allan', 'VOL • Wallace Davi', 'VOL • Huguinho', 'MC • Danilo',
    'MC • Cristian Medina', 'MC • Edenilson', 'MEI • Santiago Rodríguez',
    'PE • Jordan Barrera', 'PE • Álvaro Montoro', 'PE • Matheus Martins',
    'PD • Nathan Fernandes', 'PD • Júnior Santos', 'PD • Lucas Villalba',
    'SA • Joaquín Correa', 'ATA • Arthur Cabral', 'ATA • Chris Ramos', 'ATA • Kadir Barría',
  ],
  Fluminense: [
    'ZAG • Juan Pablo Freytes', 'ZAG • Julián Milán', 'ZAG • Jemmes', 'ZAG • Ignacio',
    'ZAG • Igor Rabello', 'ZAG • Davi Schuindt', 'LE • Guilherme Arana', 'LE • Renê',
    'LD • Samuel Xavier', 'LD • Guga', 'LD • Júlio Fidélis', 'VOL • Martinelli',
    'VOL • Facundo Bernal', 'VOL • Otávio', 'MC • Hércules', 'MC • Nonato', 'MC • Alisson',
    'MEI • Jefferson Savarino', 'MEI • Luciano Acosta', 'MEI • David Terans', 'MEI • Ganso',
    'PE • Yeferson Soteldo', 'PE • Matheus Reis', 'PD • Agustín Canobbio', 'PD • Riquelme',
    'PD • Kevin Serna', 'ATA • John Kennedy', 'ATA • Rodrigo Castillo', 'ATA • Germán Cano',
  ],
  Bahia: [
    'ZAG • Santiago Ramos Mingo', 'ZAG • Kanu', 'ZAG • David Duarte', 'ZAG • Luiz Gustavo',
    'ZAG • Marcos Victor', 'ZAG • Fred Gomes', 'LE • Luciano Juba', 'LE • Iago',
    'LE • Zé Guilherme', 'LD • Gilberto', 'LD • Romário Gómez', 'VOL • Caio Alexandre',
    'VOL • Nicolás Acevedo', 'VOL • Erick', 'MC • Jean Lucas', 'MC • Rodrigo Nestor',
    'MEI • Everton Ribeiro', 'MEI • Roger Gabriel', 'PE • Erick Pulga', 'PD • Ruan Pablo',
    'PD • Mateo Sanabria', 'PD • Cristian Oliveira', 'PD • Michel Araújo', 'PD • Ademir',
    'ATA • Dell', 'ATA • Willian José', 'ATA • Everaldo',
  ],
  'Grêmio': [
    'ZAG • Viery', 'ZAG • Gustavo Martins', 'ZAG • Wagner Leonardo', 'ZAG • Fabián Balbuena',
    'ZAG • Walter Kannemann', 'LE • Luiz Eduardo', 'LE • Marlon', 'LE • Caio Paulista',
    'LE • Pedro Gabriel', 'LD • Cristian Pavón', 'LD • João Pedro', 'LD • Marcos Rocha',
    'LD • Leonel Pérez', 'VOL • Erick Noriega', 'VOL • Mathías Villasanti', 'VOL • Dodi',
    'MC • Juan Nardoni', 'MC • Arthur Melo', 'MC • Tiaguinho', 'MC • Gabriel Mec',
    'MEI • Miguel Monsalve', 'MEI • Riquelme', 'PE • Francis Amuzu', 'PE • Willian',
    'PD • Tetê', 'PD • José Enamorado', 'PD • Roger', 'ATA • Carlos Vinícius',
    'ATA • André Henrique', 'ATA • Martin Braithwaite',
  ],
  Vasco: [
    'ZAG • Robert Renan', 'ZAG • Carlos Cuesta', 'ZAG • Alan Saldivia', 'ZAG • Lucas Freitas',
    'ZAG • Wallace Falcão', 'LE • Cuiabano', 'LE • Lucas Piton', 'LD • Paulo Henrique',
    'LD • José Luis Rodríguez', 'LD • JV Fonseca', 'VOL • Cauan Barros',
    'VOL • Thiago Mendes', 'VOL • Mateus Carvalho', 'VOL • Hugo Moura', 'VOL • Jair',
    'VOL • Lucas Eduardo', 'MC • JP', 'MC • Tchê Tchê', 'MEI • Matheus França',
    'MEI • Johan Rojas', 'MEI • Lukas Zuccarello', 'PE • Andrés Gómez', 'PE • David',
    'PD • Nuno Moreira', 'PD • Marino Hinestroza', 'PD • Adson', 'ATA • Brenner',
    'ATA • Claudio Spinelli',
  ],
  Santos: [
    'ZAG • Lucas Veríssimo', 'ZAG • Adonis Frías', 'ZAG • Zé Ivaldo', 'ZAG • Alexis Duarte',
    'ZAG • Juan Perea', 'ZAG • João Ananias', 'ZAG • Alex', 'ZAG • João Alencar',
    'LE • Vinícius Lira', 'LE • Gonzalo Escobar', 'LD • Igor Vinícius', 'LD • Mayke',
    'VOL • Cristiano Oliveira', 'VOL • Willian Arão', 'VOL • João Schmidt',
    'VOL • Gustavinho', 'VOL • Tomás Rincón', 'MC • Gabriel Bontempo',
    'MC • Gabriel Menino', 'MC • Zé Rafael', 'MC • Jefferson Alves Vasconcellos',
    'MEI • Neymar', 'MEI • Miguelito', 'MEI • Thaciano', 'PE • Álvaro Barreal',
    'PE • Moisés', 'PE • Mateus Xavier', 'PD • Benjamín Rollheiser',
    'PD • Robinho Junior', 'PD • Enzo Boer', 'ATA • Rony', 'ATA • Gabriel Barbosa',
    'ATA • Lautaro Díaz',
  ],
  Bragantino: [
    'ZAG • Gustavo Marques', 'ZAG • Guzmán Rodríguez', 'ZAG • Pedro Henrique', 'ZAG • Alix',
    'ZAG • Eduardo', 'LE • Juninho Capixaba', 'LE • Vanderlan', 'LD • Cauã Nascimento',
    "LD • Agustín Sant'Anna", 'LD • José Andrés Hurtado', 'LD • Ryan Augusto',
    'VOL • Fabinho', 'VOL • Matheus Fernandes', 'VOL • Gabriel', 'MC • Ignacio Sosa',
    'MC • Eric Ramires', 'MC • Gustavo Neves', 'MC • Praxedes', 'MC • João Neto',
    'MEI • Rodriguinho', 'MEI • Bruninho', 'MEI • Marcelinho Braz', 'PE • Vinicinho',
    'PE • Henry Mosquera', 'PD • Davi Gomes', 'PD • Lucas Barbosa', 'PD • José Herrera',
    'PD • Kawe', 'ATA • Isidro Pitta', 'ATA • Fernando', 'ATA • Eduardo Sasha',
    'ATA • Gabriel Novaes',
  ],
  'Atlético-MG': [
    'ZAG • Lyanco', 'ZAG • Ruan', 'ZAG • Iván Román', 'ZAG • Júnior Alonso',
    'ZAG • Vitor Hugo', 'ZAG • Vitão', 'LE • Renan Lodi', 'LE • Kauã Pessini',
    'LD • Natanael', 'LD • Ángelo Preciado', 'VOL • Alexander', 'VOL • Tomás Pérez',
    'VOL • Patrick', 'MC • Victor Hugo', 'MC • Alan Franco', 'MC • Maycon',
    'MC • Mamady Cissé', 'MC • Índio', 'MEI • Gustavo Scarpa', 'MEI • Igor Gomes',
    'MEI • Reinier', 'MEI • Mateus Iseppe', 'PE • Tomás Cuello', 'PE • Dudu',
    'PE • Bernard', 'PD • Alan Minda', 'SA • Caio Sampaio', 'ATA • Mateo Cassierra',
    'ATA • Hulk',
  ],
  'São Paulo': [
    'ZAG • Alan Franco', 'ZAG • Matheus Dória', 'ZAG • Sabino', 'ZAG • Matheus Belém',
    'ZAG • Rafael Tolói', 'ZAG • Robert Arboleda', 'LE • Enzo Díaz', 'LE • Wendell',
    'LE • Nicolas', 'LD • Maik', 'LD • João Moreira', 'LD • Lucas Ramon',
    'LD • Cédric Soares', 'VOL • Pablo Maia', 'VOL • Felipe Negrucci', 'VOL • Luam',
    'VOL • Hugo Leonardo', 'MC • Marcos Antônio', 'MC • Damián Bobadilla',
    'MC • Danielzinho', 'MC • Jhonnderry', 'MEI • Cauly', 'MEI • Pedro Ferreira',
    'PE • Ferreirinha', 'PE • Lucca', 'PD • Tetê', 'PD • Artur', 'PD • Lucas Moura',
    'ATA • Ryan Francisco', 'ATA • Gonzalo Tapia', 'ATA • André Silva',
    'ATA • Jonathan Calleri', 'ATA • Luciano', 'ATA • Paulinho',
  ],
  Internacional: [
    'ZAG • Victor Gabriel', 'ZAG • Félix Torres', 'ZAG • Juninho', 'ZAG • Clayton',
    'ZAG • Gabriel Mercado', 'LE • Alexandro Bernabei', 'LE • Matheus Bahia',
    'LD • Bruno Gomes', 'LD • Braian Aguirre', 'VOL • Rodrigo Villagra',
    'VOL • Thiago Maia', 'VOL • Ronaldo', 'VOL • Richard', 'VOL • Benjamín',
    'MC • Alan Rodríguez', 'MC • Paulinho Paula', 'MC • Bruno Henrique',
    'MEI • Alan Patrick', 'MEI • Alex', 'MEI • Yago Noal', 'PE • Johan Carbonero',
    'PE • Vitinho', 'PD • Kayky', 'PD • Bruno Tabata', 'ATA • Rafael Borré',
    'ATA • Alemanno', 'ATA • Raykkonen',
  ],
  Athletico: [
    'ZAG • Arthur Dias', 'ZAG • Carlos Terán', 'ZAG • Juan Felipe Aguirre', 'ZAG • Léo',
    'LE • Lucas Esquivel', 'LE • Léo Derik', 'LD • Gastón Benavídez',
    'LD • Gilberto Junior', 'LD • Dudu', 'VOL • Luiz Gustavo', 'MC • Juan Portilla',
    'MC • João Cruz', 'MC • Felipinho', 'MC • Jadson', 'MC • Alejandro García',
    'MEI • Dudu', 'MEI • Bruno Zapelli', 'MEI • Chiqueti', 'PE • Julimar',
    'PE • Isaac', 'PE • Stiven Mendoza', 'PD • Daniel Aguilar', 'PD • Bruninho',
    'PD • Leozinho', 'ATA • Kevin Viveros', 'ATA • Renan Peixoto', 'ATA • Renan Viana',
  ],
  'Vitória': [
    'ZAG • Cacá', 'ZAG • Edu Ribeiro', 'ZAG • Camutanga', 'ZAG • Neris',
    'LE • Luan Cândido', 'LE • Ramon', 'LE • Jamerson', 'LD • Claudinho',
    'LD • Nathan Mendes', 'LD • Mateus Silva', 'LD • Baralhas', 'VOL • Rúben Ismael',
    'VOL • Ronald', 'VOL • Dudu', 'VOL • Caíque Gonçalves', 'VOL • Zé Breno',
    'MC • Zé Vitor', 'MEI • Matheuzinho', 'MEI • Aitor Cantalapiedra',
    'MEI • Emmanuel Martínez', 'MEI • Pablo', 'PE • Diego Tardzia', 'PE • René',
    'PE • Lucas Braga', 'PE • Kike Saverio', 'PE • Anderson Pato', 'PD • Erick',
    'PD • Lucas Silva', 'PD • Marinho', 'PD • Osvaldo', 'ATA • Pedro Henrique',
    'ATA • Renato Kayzer', 'ATA • Fabri', 'ATA • Renzo López',
  ],
  Coritiba: [
    'ZAG • Jacy', 'ZAG • Tiago Coser', 'ZAG • Maicon', 'ZAG • Rodrigo Moledo',
    'ZAG • Thiago Santos', 'LE • Felipe Jonatan', 'LE • João Almeida', 'LE • Bruno Melo',
    'LE • JP Chermont', 'LD • Tiago', 'VOL • Vini Paulista', 'VOL • Wallisson',
    'VOL • Willian Oliveira', 'MC • Sebastián Gómez', 'MEI • Fernando Sobral',
    'MEI • Gustavo', 'MEI • Josué', 'PE • Joaquín Lavega', 'PE • Breno Lopes',
    'PD • Keno', 'PD • Lucas Ronier', 'PD • Fabinho', 'ATA • Pedro Rocha',
    'ATA • Renato Marques', 'ATA • Rodrigo Rodrigues',
  ],
  Mirassol: [
    'ZAG • Willian Machado', 'ZAG • João Victor', 'ZAG • Lucas Oliveira',
    'ZAG • Rodrigo', 'LE • Reinaldo', 'LE • Victor Luís', 'LD • Igor Cariús',
    'LD • Igor Formiga', 'LD • Daniel Borges', 'VOL • Neto Moura', 'VOL • Yuri Lara',
    'VOL • Gabriel Pires', 'MC • Denilson', 'MC • José Aldo', 'MEI • Shaylon',
    'MEI • Eduardo', 'MEI • Lucas Mugni', 'MEI • Chico Kim', 'PE • Alesson',
    'PE • Antonio Galeano', 'PD • Nogueira', 'PD • Everton Galdino',
    'PD • Carlos Eduardo', 'PD • Luiz Filipe', 'ATA • Nathan Fogaça',
    'ATA • Edson Carioca', 'ATA • André Luís', 'ATA • Tiquinho Soares',
  ],
  Remo: [
    'ZAG • Tchamba', 'ZAG • Kayky Almeida', 'ZAG • Thalisson', 'ZAG • Léo Andrade',
    'ZAG • Marlon', 'ZAG • Cristian Tassano', 'LE • Brian Cuñé', 'LE • Mayk',
    'LE • Edson Kauã', 'LD • João Lucas', 'LD • Matheus Alexandre', 'LD • Marcelinho',
    'VOL • Leonel Picco', 'VOL • Patrick de Paula', 'VOL • Zé Wellison',
    'VOL • David Braga', 'VOL • Zé Ricardo', 'VOL • Panagiotis Tachtsidis',
    'VOL • Freitas', 'MC • Patrick', 'MC • Giovanni Pavani', 'MC • Franco Catarozzi',
    'MEI • Vitor Bueno', 'PE • Diego Hernández', 'PE • Jajá', 'PE • Jaderson',
    'PE • Alef Manga', 'PD • Yago Pikachu', 'ATA • Gabriel Talieri', 'ATA • Carlinhos',
    'ATA • João Pedro', 'ATA • Rafael Monte', 'ATA • Gabriel Poveda',
    'ATA • Eduardo Melo',
  ],
  Chapecoense: [
    'ZAG • Doma', 'ZAG • João Paulo', 'ZAG • Victor Caetano', 'ZAG • Bruno Leonardo',
    'ZAG • Rafael Thyere', 'ZAG • Kauan Faria', 'LE • Vinícius Eduardo',
    'LE • Mancha', 'LE • Walter Clar', 'LE • Bruno Pacheco', 'LE • Da Silva',
    'LD • Marcos Vinícius', 'LD • Everton', 'LD • Gustavo Talles', 'VOL • Carvalheira',
    'VOL • Camilo', 'VOL • Higor Meritão', 'VOL • Vinícius Balieiro',
    'MC • João Vitor', 'MC • Bruno Matias', 'MC • David Antunes', 'MEI • Robert Santos',
    'MEI • Jean Carlos', 'MEI • Giovanni Augusto', 'MEI • Wermeson', 'PE • Ítalo Vargas',
    'PE • Maurício Garcez', 'PE • Ênio', 'PD • Kevin Ramírez', 'PD • Marcinho',
    'PD • Rubens', 'ATA • Neto Pessoa', 'ATA • Yannick Bolasie', 'ATA • João Bom',
  ],
};
